// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9B2oC5OaEKwC6ZVCXTtZWKlTOapdIf1w',
    appId: '1:69530535913:web:d36b804222e8cd440a6d78',
    messagingSenderId: '69530535913',
    projectId: 'antiwellbeing',
    authDomain: 'antiwellbeing.firebaseapp.com',
    storageBucket: 'antiwellbeing.firebasestorage.app',
    measurementId: 'G-H1ZZPN2NHH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_kr5q2Xd5SzF4ETW_xVixEhmun50Z8pA',
    appId: '1:69530535913:android:643712801f4c26d30a6d78',
    messagingSenderId: '69530535913',
    projectId: 'antiwellbeing',
    storageBucket: 'antiwellbeing.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALR3uWQhGYxSGbnDwjAk9PwccClbGfg3Y',
    appId: '1:69530535913:ios:8bcd6e75c37946350a6d78',
    messagingSenderId: '69530535913',
    projectId: 'antiwellbeing',
    storageBucket: 'antiwellbeing.firebasestorage.app',
    iosClientId: '69530535913-6nv6r7ee2tnfbk9f88honmh83b94p67a.apps.googleusercontent.com',
    iosBundleId: 'com.example.antiWellbeing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALR3uWQhGYxSGbnDwjAk9PwccClbGfg3Y',
    appId: '1:69530535913:ios:8bcd6e75c37946350a6d78',
    messagingSenderId: '69530535913',
    projectId: 'antiwellbeing',
    storageBucket: 'antiwellbeing.firebasestorage.app',
    iosClientId: '69530535913-6nv6r7ee2tnfbk9f88honmh83b94p67a.apps.googleusercontent.com',
    iosBundleId: 'com.example.antiWellbeing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9B2oC5OaEKwC6ZVCXTtZWKlTOapdIf1w',
    appId: '1:69530535913:web:c4bcccb949f4f4bf0a6d78',
    messagingSenderId: '69530535913',
    projectId: 'antiwellbeing',
    authDomain: 'antiwellbeing.firebaseapp.com',
    storageBucket: 'antiwellbeing.firebasestorage.app',
    measurementId: 'G-K0EFP4V79T',
  );

}